name: flutter_plugins_assets
description: Images and fonts for the Flutter plugins
version: 0.0.2
author: Yann-Cyril Pelud <yann@fidelisa.com>
homepage: https://github.com/fidelisa/flutter_plugins

environment:
  sdk: ">=1.19.0 <3.0.0"
